### ISSUE TITLE
Error with the CocoaHeads-August

### ISSUE THREAD

**Issue by darthpelo** [nvh/DataSourceable-presentation#1]
Hi @nvh I tried to open the last playground, but I have this error:
_Couldn't load settings from contents.xcplayground_

No issues with the others.

Thanks

**Comment by nvh** [comment]
The last playground was created using XCode 8 beta 6. Could you try opening it with that?

**Comment by nvh** [comment]
I seem not to have added the completed playground, It should be fixed with the latest commit!

**Comment by darthpelo** [comment]
@nvh Thanks!
